pdo.options:
  dsn: mysql:host=localhost;dbname=php_workshop;charset=UTF8
  username: workshop
  password: workshop
  options:
  attributes:

emotion_api:
  key: 45d86912aed0470abb9d6c40eeebff47 #or c1c39387d15740b188ce446ae0f7a8ff

debug: false
