# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "workshop" do |workshop|
        workshop.vm.box       = "bento/ubuntu-16.04"
        workshop.vm.hostname  = "workshop.local"
        workshop.vm.network "private_network", ip: "192.168.13.37"
    end

    config.vm.provider "virtualbox" do |vbox|
        vbox.memory = 1024
        vbox.cpus   = 2
    end

    config.vm.provision "ansible_local" do |ansible|
        ansible.inventory_path    = "inventories/dev/hosts"
        ansible.playbook          = "provision/athena.yml"
        ansible.limit             = "all"
    end

    config.vm.provision "ansible_local" do |ansible|
        ansible.inventory_path    = "inventories/dev/hosts"
        ansible.playbook          = "provision/provision.yml"
        ansible.limit             = "all"
    end
end
